# SPDX-License-Identifier: MPL-2.0
module QUBODecomposition

import MathOptInterface as MOI
import QUBODrivers
import QUBOTools
const VI = MOI.VariableIndex

# The generated storage owns MOI copying, fixed-variable reconstruction and starts.
# The public composite wraps it so its keyword constructor and validation do not
# overwrite methods generated by @setup during precompilation.
QUBODrivers.@setup ModelStorage begin
    name = "QUBODecomposition model storage"
    version = v"0.1.0"
end

include("optimizer.jl")
include("solve.jl")

end
