# SPDX-License-Identifier: MPL-2.0
module QUBODecomposition

import MathOptInterface as MOI
import QUBODrivers
import QUBOTools
import Random
const VI = MOI.VariableIndex
const PACKAGE_VERSION = pkgversion(@__MODULE__)

# The generated storage owns MOI copying, fixed-variable reconstruction and starts.
# The public composite wraps it so its keyword constructor and validation do not
# overwrite methods generated by @setup during precompilation.
QUBODrivers.@setup ModelStorage begin
    name = "QUBODecomposition model storage"
    version = PACKAGE_VERSION
end

include("optimizer.jl")
include("solve.jl")
include("serial.jl")
include("separator.jl")

end
